// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPRT9VTmWYaDNCs3Cep-Tck2rFaIwST98',
    appId: '1:571377771654:web:1299f735fa4fe8f622dd07',
    messagingSenderId: '571377771654',
    projectId: 'mindwell-390bb',
    authDomain: 'mindwell-390bb.firebaseapp.com',
    storageBucket: 'mindwell-390bb.appspot.com',
    measurementId: 'G-54G1XYP0MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSq9WP2nl7-d9YTqafaxw2lCbTPHENYDg',
    appId: '1:571377771654:android:d3cd34bcaf42df5122dd07',
    messagingSenderId: '571377771654',
    projectId: 'mindwell-390bb',
    storageBucket: 'mindwell-390bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1tt6NM_3AE8pbJfJu1vXE2uwNqwrmEhU',
    appId: '1:571377771654:ios:5ba9aea1b74ac92322dd07',
    messagingSenderId: '571377771654',
    projectId: 'mindwell-390bb',
    storageBucket: 'mindwell-390bb.appspot.com',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1tt6NM_3AE8pbJfJu1vXE2uwNqwrmEhU',
    appId: '1:571377771654:ios:170ef0dadae065cd22dd07',
    messagingSenderId: '571377771654',
    projectId: 'mindwell-390bb',
    storageBucket: 'mindwell-390bb.appspot.com',
    iosBundleId: 'com.example.adminApp.RunnerTests',
  );
}
